---
- ros_topic_name: "/x500/command/motor_speed_cmd"
  gz_topic_name: "/x500/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: "BIDIRECTIONAL"
- ros_topic_name: "/x500/imu"
  gz_topic_name: "/x500/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/x500/magnetometer"
  gz_topic_name: "/x500/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/x500/air_pressure"
  gz_topic_name: "/x500/air_pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: "GZ_TO_ROS"